node{
    stage('SCM Checkout'){
        git 'https://github.com/haribabu-git/springboot1'    
    }
    tools{
       jdk 'JAVA_HOME'
    }
    stage ("initialize") {
    steps {
    sh '''
        echo "PATH = ${PATH}"
       '''
    }
  
}
