node{
    
    
    jdk = tool name: 'JAVA_HOME'
  env.JAVA_HOME = "${jdk}"

  echo "jdk installation path is: ${jdk}"
  echo "jdk version is: ${jdk}/bin/java -version"

  // next 2 are equivalents
  bat "${jdk}/bin/java -version"

  // note that simple quote strings are not evaluated by Groovy
  // substitution is done by shell script using environment
  bat '$JAVA_HOME/bin/java -version'
   
    
  
}
